### ISSUE TITLE
Multiple Database Support?

### ISSUE THREAD

**Issue by Shu-Ji** [sqls-server/sqls#121]
I have the a mysql like this:
```sql
SELECT *
FROM db1.tb1 tb1_alias
JOIN db2.tb2 tb2_alias ON tb1_alias.<cursor_1> = tb2_alias.<cursor_2>
```

<cursor_1> will autocomplete, but cursor_2 not.

db1 and db2 in a same mysql server instance.

config:
```yml
# Set to true to use lowercase keywords instead of uppercase.
lowercaseKeywords: false
connections:
    -   alias: mysql1
        driver: mysql
        dataSourceName: myuser:mypwd@tcp(127.0.0.1:3306)/db1
```

If I add db2 in the yml file, still not work:
```yml
```yml
# Set to true to use lowercase keywords instead of uppercase.
lowercaseKeywords: false
connections:
    -   alias: mysql1
        driver: mysql
        dataSourceName: myuser:mypwd@tcp(127.0.0.1:3306)/db1

    -   alias: mysql1
        driver: mysql
        dataSourceName: myuser:mypwd@tcp(127.0.0.1:3306)/db2
```
