### ISSUE TITLE
Other RDBMS support

### ISSUE THREAD

**Issue by PorcoRosso85** [sqls-server/sqls#159]
**Describe the solution you'd like**
I want to use this server for any postgres server

**Additional context**
https://github.com/sqls-server/sqls
This shows us folowing:

MySQL([Go-MySQL-Driver](https://github.com/go-sql-driver/mysql))
PostgreSQL([pgx](https://github.com/jackc/pgx))
SQLite3([go-sqlite3](https://github.com/mattn/go-sqlite3))
MSSQL([go-mssqldb](https://github.com/denisenkom/go-mssqldb))
H2([pgx](https://github.com/CodinGame/h2go))
Vertica([vertica-sql-go](https://github.com/vertica/vertica-sql-go))

This means that sqls server doesn't suppor postgres server which doesn't use these engine?
My backend is on nodejs and 'pg' is as postgres client  library.

OR
sqls's support is not related to client/engines like 'pg' or 'pgx'
if we set a file like bellow?

```yaml
# Set to true to use lowercase keywords instead of uppercase.
lowercaseKeywords: false
connections:
  - alias: dsn_mysql
    driver: mysql
    dataSourceName: root:root@tcp(127.0.0.1:13306)/world
  - alias: individual_mysql
    driver: mysql
    proto: tcp
    user: root
    passwd: root
    host: 127.0.0.1
    port: 13306
    dbName: world
    params:
      autocommit: "true"
      tls: skip-verify
  - alias: mysql_via_ssh
    driver: mysql
    proto: tcp
    user: admin
    passwd: Q+ACgv12ABx/
    host: 192.168.121.163
    port: 3306
    dbName: world
    sshConfig:
      host: 192.168.121.168
      port: 22
      user: sshuser
      passPhrase: ssspass
      privateKey: /home/sqls-server/.ssh/id_rsa
  - alias: dsn_vertica
    driver: vertica
    dataSourceName: vertica://user:pass@host:5433/dbname
```
