### ISSUE TITLE
Document/Add Helix support

### ISSUE THREAD

**Issue by H2WO4** [sqls-server/sqls#163]
**Is your feature request related to a problem? Please describe.**
Using `sqls` with [helix](https://github.com/helix-editor/helix) is possible; but incomplete.

**Describe the solution you'd like**
Similarly to the individual editors plugins done for vim and others, to have more "specialized" support for Helix.
Or at least document what config options are available in order to be able to "hack in" support.

Here is what works:
- Tables and columns autocomplete (sometimes, line breaks seem to break it)
- Tables and columns hover (markdown tables rendering is currently broken, but that comes from helix: [bug report](https://github.com/helix-editor/helix/issues/11175))

Here is what doesn't seems to work:
- Keyword autocomplete
- Tables and columns autocomplete needs to often be brought up manually and are sometimes unable to work from a "blank start" (as in you need to start typing at least 1 character for it to work)
- Signature help
- Commands

**Describe alternatives you've considered**
Using the other [SQL LSP](https://github.com/joe-re/sql-language-server), or switching editor; but neither option is a solution.

**Additional context**
I was not able to figure out why completion doesn't work; but the reason why commands do not seems to be that the commands are registered as code actions, instead of workspace commands.

**Comment by H2WO4** [comment]
A straightforward configuration should have `sqls` somewhat working.

Here's my `languages.toml`:

```toml
[[language]]
name = "sql"
autoformat = false
language-servers = ["sqls"]

# ...

[language-server.sqls]
command = "sqls"
```

You should also have a `sqls/config.yml` set up:

```yml
connections:
- alias: "connection-name"
  driver: "your-db"
  dataSourceName: "url://to:your@db/"
```

You may need to change the `command` field to the absolute path to the `sqls` executable if it is not in your `$PATH`.

If you need info for troubleshooting, the `:log-open` helix command is very useful.
