### ISSUE TITLE
Neovim Nightly with Lspconfig not working

### ISSUE THREAD

**Issue by yngwi** [sqls-server/sqls#166]
Hi,

I’m trying to use `sqls` with `Neovim` and `Lspconfig`. My problem is, that even though the server seems to start and connect just fine (`LspInfo` lists the server and the error message when no database connection is available pops up with wrong config but stays silent when a correct config file is present) but Hover and autocomplete don’t work and when I try to execute a code action (they are correctly listed), I get the following notification (for instance): `Language server sqls does not support command showTables`.

The Server is configured as follows:

```lua
local utils = require("utils")
local lsp_utils = require("lspconfig.util")

local config = function()
	local cmd = { "sqls" }
	if utils.has_in_cwd(".sqls.yml") then
		cmd = { "sqls", "-config", ".sqls.yml" }
	end
	return {
		cmd = cmd,
		single_file_support = false,
		root_dir = lsp_utils.root_pattern(".sqls.yml", ".git"),
	}
end

return config()
```
.sqls.yml is for instance
```yml
lowercaseKeywords: false
connections:
  - alias: localhost
    driver: postgresql
    dataSourceName: host=pg port=5432 user=postgres password=password dbname=tm sslmode=disable
```
The database is in a docker container while sqls and nvim runs in another Linux container with sqls and other tools present on path inside. 

```sh
⬢ [Docker] ❯ sqls --version
sqls version Version:0.2.28, Revision:HEAD
```

Any pointers as to what could be the reason?
